baseURL = 'https://example.org/'
languageCode = 'nl-BE'
title = 'E-Trico'
theme = 'hugo-universal-theme'
defaultContentLanguage = 'nl'

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "X"
    url = "https://x.com"
    pre = "<i class='fab fa-2x fa-x-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
